# Generated by Django 4.0.2 on 2022-07-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OEEValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partid', models.CharField(max_length=255)),
                ('machineid', models.CharField(max_length=255)),
                ('oeevalue', models.FloatField()),
                ('Avalue', models.FloatField()),
                ('Pvalue', models.FloatField()),
                ('Qvalue', models.FloatField()),
            ],
        ),
    ]
