# Generated by Django 4.0.5 on 2022-07-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_oeevalues_partid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthenticateUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
            ],
        ),
    ]
